stages:
  - build
  - release

variables:
  RELEASE_TAG: $CI_COMMIT_TAG

build_package:
  stage: build
  image: ubuntu:latest
  before_script:
    - apt update && apt install -y make zip
  script:
    - make package VERSION=${RELEASE_TAG}
    - mv decker-${RELEASE_TAG}.zip decker-latest.zip
  artifacts:
    paths:
      - decker-${RELEASE_TAG}.zip
      - decker-latest.zip
    expire_in: 1 week

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "Releasing ${RELEASE_TAG}"
  release:
    name: "Release ${RELEASE_TAG}"
    tag_name: "${RELEASE_TAG}"
    description: "New release ${RELEASE_TAG}"
    assets:
      links:
        - name: "Download decker-${RELEASE_TAG}.zip"
          url: "${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/download"
        - name: "Latest package"
          url: "${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/download?file_type=archive"

