stages:
  - build
  - upload
  - release

variables:
  # Package version should match \A(\.?[\w\+-]+\.?)+\z regular expresion.
  # See https://docs.gitlab.com/ee/user/packages/generic_packages/#publish-a-package-file
  PACKAGE_VERSION: "${CI_COMMIT_TAG}"
  PACKAGE_BINARY: "decker-${PACKAGE_VERSION}"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/decker/${PACKAGE_VERSION}"

build:
  stage: build
  only:
    - tags
  before_script:
    - apt-get update && apt-get install -y make zip composer
    - composer --version
  script:
    - make package VERSION="${PACKAGE_VERSION}"
    - ls -lh "decker-${PACKAGE_VERSION}.zip"
  artifacts:
    paths:
      - "decker-${PACKAGE_VERSION}.zip"
    expire_in: 1 week

upload:
  stage: upload
  image: curlimages/curl:latest
  only:
    - tags
  needs: ["build"]
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
           --upload-file "${PACKAGE_BINARY}.zip" \
           "${PACKAGE_REGISTRY_URL}/${PACKAGE_BINARY}.zip"
           
release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  only:
    - tags
  needs: ["upload"]
  script:
    - |
      release-cli create \
        --name "Release ${CI_COMMIT_TAG}" \
        --tag-name "${CI_COMMIT_TAG}" \
        --description "Release for ${CI_COMMIT_TAG}" \
        --assets-link "{\"name\":\"${PACKAGE_BINARY}.zip\",\"url\":\"${PACKAGE_REGISTRY_URL}/${PACKAGE_BINARY}.zip\"}"

