services:

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 3306:3306

  wordpress:
    image: erseco/alpine-wordpress:latest
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - 8080:8080
    environment:
      max_execution_time: 300
      WP_LANGUAGE: es_ES
      WP_ADMIN_USERNAME: admin
      WP_ADMIN_PASSWORD: PLEASE_CHANGEME
      WP_DEBUG: true
      WP_PLUGINS: "sql-buddy,plugin-check,query-monitor"
      WP_SITE_URL: http://localhost:8080
      POST_CONFIGURE_COMMANDS: |
        echo "this is a test line 1"
        echo "this is a test line 2"
        wp plugin activate decker
        if ! wp user get test1 --field=ID --quiet; then
          wp user create test1 test1@example.com --role=decker_role --user_pass=test1
        fi
        if ! wp user get test2 --field=ID --quiet; then
          wp user create test2 test2@example.com --role=decker_role --user_pass=test2
        fi
        echo "Configurando entorno de pruebas..."
        # bash wp-content/plugins/decker/bin/install-wp-tests.sh wordpress wordpress wordpress mariadb latest
        # phpunit
    volumes:
      - wordpress:/var/www/html
      - ./:/var/www/html/wp-content/plugins/decker

  phpunit:
    image: wordpressdevelop/phpunit
    volumes:
      - ./:/var/www/html
    # working_dir: /app
    command: phpunit

  # tests:
  #   image: php:7.4-cli
  #   depends_on:
  #     - mariadb
  #   volumes:
  #     - ./:/var/www/html/wp-content/plugins/decker
  #   working_dir: /var/www/html/wp-content/plugins/decker
  #   environment:
  #     - WORDPRESS_DB_NAME=wordpress_test
  #     - WORDPRESS_DB_USER=wordpress
  #     - WORDPRESS_DB_PASSWORD=wordpress
  #     - WORDPRESS_DB_HOST=mariadb
  #   command: bash -c "composer install && ./bin/install-wp-tests.sh wordpress_test wordpress wordpress mariadb latest && ./vendor/bin/phpunit"


volumes:
  mariadb: null
  wordpress: null

