---
name: CI

on:
  pull_request:
  push:
    tags:
      - '*'
    branches:
      - '*' 
jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  # Adjust the version according to your needs
          extensions: mbstring, intl, curl, dom, json, pdo, mysql, xml, zip

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      # - name: Setup WP-CLI
      #   uses: godaddy-wordpress/setup-wp-cli@1

      - name: Run code linting
        run: make lint

      - name: Install gettext
        run: sudo apt-get update && sudo apt-get install -y gettext

      - name: Check untranslated strings
        run: make check-untranslated

      - name: Create Plugin ZIP Archive
        run: |
          composer archive --format=zip --dir=. --file=decker
          mkdir decker
          unzip decker.zip -d decker

      - name: Run plugin check
        uses: wordpress/plugin-check-action@v1
        with:
          build-dir: './decker'
          exclude-checks: 'image_functions'

      - name: Uninstall plugin decker
        run: |
          npx wp-env run cli wp plugin deactivate decker
          npx wp-env run cli wp plugin uninstall decker

      - name: Setup & start wp-env
        uses: godaddy-wordpress/setup-wp-env@v1
        with:
          plugins: '["."]'

      - name: Run unit tests
        run: npx wp-env run tests-cli --env-cwd=wp-content/plugins/wp-decker ./vendor/bin/phpunit


      # - name: Install plugin check
      #   run: npx wp-env run cli wp plugin install plugin-check --activate

      # - name: Run plugin check
      #   run: make check


      # - name: Run plugin check
      #   uses: wordpress/plugin-check-action@v1
      #   with:
      #     # build-dir: '.'
      #     exclude-checks: 'image_functions'
      #     slug: 'decker'
